extends Resource

class_name WeatherEffect

enum WeatherID {
	WEATHER_NONE,
	WEATHER_SUNNY_CLOUDS,
	WEATHER_SUNNY,
	WEATHER_RAIN,
	WEATHER_SNOW,
	WEATHER_RAIN_THUNDERSTORM,
	WEATHER_FOG_HORIZONTAL,
	WEATHER_VOLCANIC_ASH,
	WEATHER_SANDSTORM,
	WEATHER_FOG_DIAGONAL,
	WEATHER_UNDERWATER,
	WEATHER_SHADE,
	WEATHER_DROUGHT,
	WEATHER_DOWNPOUR,
	WEATHER_UNDERWATER_BUBBLES,
	WEATHER_FOG,
}

@export var weather: WeatherID
